# Generated by Django 2.0.7 on 2018-07-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.BigIntegerField()),
                ('user', models.CharField(max_length=15)),
                ('text', models.CharField(max_length=280)),
            ],
        ),
    ]
